package de.ralfhergert.gw2.api.v2;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum Gw2BuffConditionType {
    @JsonProperty("A.E.D.") AED,
    Aegis,
    Afterburner,
    Alacrity,
    @JsonProperty("Balanced Stance") BalancedStance,
    @JsonProperty("Berserker's Power") BerserkersPower,
    Bleeding,
    Blinded,
    Burning,
    @JsonProperty("Call of the Wild") CallOfTheWild,
    Chilled,
    Confusion,
    @JsonProperty("Continuum Shift") ContinuumShift,
    Crippled,
    Daze,
    Distortion,
    @JsonProperty("Enduring Pain") EnduringPain,
    @JsonProperty("Facet of Nature") FacetOfNature,
    @JsonProperty("Facet of Nature—Assassin") FacetOfNatureAssassin,
    @JsonProperty("Facet of Nature—Centaur") FacetOfNatureCentaur,
    @JsonProperty("Facet of Nature—Demon") FacetOfNatureDemon,
    @JsonProperty("Facet of Nature—Dwarf") FacetOfNatureDwarf,
    @JsonProperty("Facet of Nature—Dragon") FacetOfNatureDragon,
    Fear,
    @JsonProperty("Fire Aura") FireAura,
    @JsonProperty("Frost Aura") FrostAura,
    Fury,
    Immobile,
    @JsonProperty("Improved Kalla's Fervor") ImprovedKallasFervor,
    Justice,
    @JsonProperty("Kalla's Fervor") KallasFervor,
    @JsonProperty("Magnetic Aura") MagneticAura,
    Might,
    @JsonProperty("Mirage Cloak") MirageCloak,
    Poisoned,
    Protection,
    Quickness,
    Reflection,
    Regeneration,
    Resistance,
    Resolve,
    Retaliation,
    Revealed,
    @JsonProperty("Rite of the Great Dwarf") RiteOfTheGreatDwarf,
    @JsonProperty("Shocking Aura") ShockingAura,
    @JsonProperty("Signet of Stone") SignetOfStone,
    Slow,
    @JsonProperty("Spider Venom") SpiderVenom,
    Stability,
    @JsonProperty("Static Charge") StaticCharge,
    Stealth,
    @JsonProperty("Stone Resonance") StoneResonance,
    Superspeed,
    Swiftness,
    Taunt,
    @JsonProperty("Tome of Resolve") TomeOfResolve,
    Torment,
    @JsonProperty("True Nature") TrueNature,
    Unblockable,
    @JsonProperty("Unflinching Fortitude") UnflinchingFortitude,
    @JsonProperty("Utility Goggles") UtilityGoggles,
    @JsonProperty("Vampiric Mark") VampiricMark,
    Vigor,
    @JsonProperty("Virtue of Courage") VirtueOfCourage,
    @JsonProperty("Virtue of Resolve") VirtueOfResolve,
    Vulnerability,
    Weakness
}
