package de.ralfhergert.gw2.model;

import java.util.HashMap;
import java.util.Map;
import java.util.stream.Stream;

import static de.ralfhergert.gw2.model.Specialization.*;
import static de.ralfhergert.gw2.model.TraitSlot.Minor;
import static de.ralfhergert.gw2.model.TraitSlot.Major;

public enum Trait {
    RagingStorm(214, Air, 2, 1, Major, "Raging Storm"),
    ZephyrsSpeedAir(221, Air, 1, 0, Minor, "Zephyr's Speed"),
    ElectricDischarge(222, Air, 2, 0, Minor, "Electric Discharge"),
    AeromancersTraining(223, Air, 3, 0, Minor, "Aeromancer's Training"),
    OneWithAir(224, Air, 1, 1, Major, "One with Air"),
    BoltToTheHeart(226, Air, 3, 0, Major, "Bolt to the Heart"),
    ZephyrsBoon(227, Air, 1, 0, Major, "Zephyr's Boon"),
    Inscription(229, Air, 2, 0, Major, "Inscription"),
    FeroiousWinds(232, Air, 1, 2, Major, "Ferocious Winds"),
    EvasiveArcana(238, Arcane, 3, 0, Major, "Evasive Arcana"),
    ArcanePrecision(253, Arcane, 1, 0, Major, "Arcane Precision"),
    FinalShielding(257, Arcane, 2, 2, Major, "Final Shielding"),
    ElementalSurge(263, Arcane, 3, 1, Major, "Elemental Surge"),
    ElementalAttunement(264, Arcane, 2, 0, Minor, "Elemental Attunement"),
    ArcaneResurrection(265, Arcane, 2, 0, Major, "Arcane Resurrection"),
    RenewingStamina(266, Arcane, 1, 1, Major, "Renewing Stamina"),
    ArcaneProwess(268, Arcane, 1, 0, Minor, "Arcane Prowess"),
    StrengthOfStone(275, Earth, 2, 0, Major, "Strength of Stone"),
    EarthenBlessing(277, Earth, 2, 2, Major, "Earthen Blessing"),
    StoneFlesh(278, Earth, 1, 2, Minor, "Stone Flesh"),
    EarthenBlast(279, Earth, 2, 0, Minor, "Earthen Blast"),
    GeomancersTraining(280, Earth, 3, 0, Minor, "Geomancer's Training"),
    RockSolid(281, Earth, 2, 1, Major, "Rock Solid"),
    EarthsEmbrace(282, Earth, 1, 0, Major, "Earth's Embrace"),
    WrittenInStone(287, Earth, 3, 1, Major, "Written in Stone"),
    ElementalShilding(289, Earth, 1, 2, Major, "Elemental Shielding"),
    PyromancersPuissance(294, Fire, 3, 1, Major, "Pyromancer's Puissance"),
    BurningPrecision(296, Fire, 1, 0, Major, "Burning Precision"),
    Sunspot(318, Fire, 1, 0, Minor, "Sunspot"),
    PyromancersTraining(319, Fire, 3, 0, Minor, "PyromancersTraining"),
    EmpoweringFlame(320, Fire, 1, 0, Minor, "Empowering Flame"),
    BurningRage(325, Fire, 2, 0, Major, "Burning Rage"),
    Conjurer(328, Fire, 1, 1, Major, "Conjurer"),
    WrathfulSpirit(563, Zeal, 1, 0, Major, "Wrathful Spirit"),
    Retribution(565, Radiance, 2, 2, Major, "Retribution"),
    RightHandStrength(566, Radiance, 1, 1, Major, "Right-Hand Strength"),
    RadiantFire(567, Radiance, 2, 1, Major, "Radiant Fire"),
    RadiantPower(568, Radiance, 0, 2, Minor, "Radiant Power"),
    RenewedJustice(571, Radiance, 2, 0, Minor, "Renewed Justice"),
    JusticeIsBlind(572, Radiance, 1, 0, Minor, "Justice is Blind"),
    HealersRetribution(574, Radiance, 1, 2, Major, "Healer's Retribution"),
    InnerFire(577, Radiance, 1, 0, Major, "Inner Fire"),
    WrathOfJustice(578, Radiance, 2, 0, Major, "Wrath of Justice"),
    PerfectInscriptions(579, Radiance, 3, 1, Major, "Perfect Inscriptions"),
    BindingJeopardy(628, Zeal, 2, 0, Major, "Binding Jeopardy"),
    FieryWrath(634, Zeal, 1, 1, Major, "Fiery Wrath"),
    EternalArmory(635, Zeal, 3, 0, Major, "Eternal Armory"),
    ShatteredAegis(637, Zeal, 3, 1, Major, "Shattered Aegis"),
    SymbolicExposure(646, Zeal, 0, 1, Minor, "Symbolic Exposure"),
    ZealotsSpeed(648, Zeal, 0, 0, Minor, "Zeolot's Speed"),
    SymbolicPower(649, Zeal, 3, 0, Minor, "Symbolic Power"),
    ZealousBlade(653, Zeal, 2, 1, Major, "Zealous Blade"),
    KindledZeal(1556, Zeal, 2, 2, Major, "Kindled Zeal"),
    RighteousInstincts(1683, Radiance, 3, 2, Major, "Righteous Instincts"),
    AmplifiedWrath(1686, Radiance, 3, 0, Major, "Amplified Wrath"),
    ZealousScepter(1925, Zeal, 1, 2, Major, "Zealous Scepter"),
    SymbolicAvenger(2017, Zeal, 3, 2, Major, "Symbolic Avenger"),

    PowerOverwhelming(334, Fire, 2, 2, Major, "Power Overwhelming"),
    BurningFire(335, Fire, 1, 2, Major, "Burning Fire"),
    SmotheringAuras(340, Fire, 2, 1, Major, "Smothering Auras"),
    SoothingIce(348, Water, 1, 0, Major, "Soothing Ice"),
    FlowLikeWater(349, Water, 2, 2, Major, "Flow like Water"),
    SoothingMist(350, Water, 1, 0, Minor, "Soothing Mist"),
    HealingRipple(351, Water, 2, 0, Minor, "Healing Ripple"),
    CleansingWave(358, Water, 2, 1, Major, "Cleansing Wave"),
    StopDropAndRoll(360, Water, 1, 2, Major, "Stop, Drop, and Roll"),
    PowerfulAura(361, Water, 3, 1, Major, "Powerful Aura"),
    CleansingWater(362, Water, 3, 0, Major, "Cleansing Water"),
    PiercingShards(363, Water, 1, 1, Major, "Piercing Shards"),
    SoothingDisruption(364, Water, 2, 0, Major, "Soothing Disruption"),
    OverShield(394, Inventions, 1, 0, Major, "Over Shield"),
    InvigoratingSpeed(396, Alchemy, 1, 0, Major, "Invigorating Speed"),
    CompoundingChemicals(413, Alchemy, 3, 0, Minor, "Compounding Chemicals"),
    ShapedCharge(429, Explosives, 3, 0, Minor, "Shaped Charge"),
    EvasivePowderKeg(432, Explosives, 1, 0, Minor, "Evasive Powder Keg"),
    IncendiaryPowder(433, Firearms, 3, 2, Major, "Incendiary Powder"),
    MechaLegs(445, Inventions, 2, 2, Major, "Mecha Legs"),
    HiddenFlask(468, Alchemy, 1, 0, Minor, "Hidden Flask"),
    EmergencyElixir(469, Alchemy, 2, 1, Major, "Emergency Elixir"),
    BackpackRegenerator(470, Alchemy, 2, 2, Major, "Backpack Regenerator"),
    AnticorrosionPlating(472, Inventions, 3, 0, Major, "Anticorrosion Plating"),
    HGH(473, Alchemy, 3, 0, Major, "HGH"),
    AimAssistedRocket(482, Explosives, 2, 0, Major, "Aim-Assisted Rocket"),
    Transmute(487, Alchemy, 2, 0, Minor, "Transmute"),
    Shrapnel(505, Explosives, 3, 1, Major, "Shrapnel"),
    AutodefenseBombDispenser(507, Inventions, 1, 2, Major, "Autodefense Bomb Dispenser"),
    ReconstructionEnclosure(508, Inventions, 2, 0, Minor, "Reconstruction Enclosure"),
    ProtectionInjection(509, Alchemy, 1, 1, Major, "Protection Injection"),
    Juggernaut(510, Firearms, 3, 0, Major, "Juggernaut"),
    StreamlinedKits(512, Tools, 2, 0, Major, "Streamlined Kits"),
    Grenadier(514, Explosives, 1, 0, Major, "Grenadier"),
    Sharpshooter(515, Firearms, 1, 0, Minor, "Sharpshooter"),
    SerratedSteel(516, Firearms, 3, 0, Minor, "Serrated Steel"),
    SteelPackedPowder(517, Explosives, 2, 0, Minor, "Steel-Packed Powder"),
    CleansingSynergy(518, Inventions, 1, 0, Minor, "Cleansing Synergy"),
    EnergyAmplifier(519, Inventions, 3, 0, Minor, "Energy Amplifier"),
    ComebackCure(520, Alchemy, 2, 0, Major, "Comeback Cure"),
    HealthInsurance(521, Alchemy, 1, 2, Major, "Health Insurance"),
    AdrenalImplant(523, Tools, 3, 1, Major, "Adrenal Implant"),
    BlastingZone(525, Explosives, 1, 1, Major, "Blasting Zone"),
    ModifiedAmmunition(526, Firearms, 3, 1, Major, "Modified Ammunition"),
    PowerWrench(531, Tools, 1, 2, Major, "Power Wrench"),
    StaticDischarge(532, Tools, 1, 0, Major, "Static Discharge"),
    HematicFocus(536, Firearms, 2, 0, Minor, "Hematic Focus"),
    PureOfHeart(549, Honor, 2, 1, Major, "Pure of Heart"),
    SelflessDaring(551, Honor, 2, 0, Minor, "Selfless Daring"),
    PureOfVoice(553, Honor, 3, 0, Major, "Pure of Voice"),
    BattlePresence(554, Virtues, 3, 1, Major, "Battle Presence"),
    HonorableStaff(557, Honor, 2, 0, Major, "Honorable Staff"),
    WritOfPersistence(558, Honor, 3, 1, Major, "Writ of Persistence"),
    ProtectiveReviver(559, Honor, 1, 1, Major, "Protective Reviver"),
    EmpoweringMight(562, Honor, 2, 2, Major, "Empowering Might"),
    VigorousPrecision(564, Honor, 1, 0, Minor, "Vigorous Precision"),
    StalwartDefender(580, Valor, 2, 0, Major, "Stalwart Defender"),
    SmitersBoon(581, Valor, 1, 1, Major, "Smiter's Boon"),
    ValorousDefense(582, Valor, 1, 0, Minor, "Valorous Defense"),
    MightOfTheProtector(583, Valor, 3, 0, Minor, "Might of the Protector"),
    StrengthInNumbers(584, Valor, 2, 1, Major, "Strength in Numbers"),
    AltruisticHealing(585, Valor, 3, 0, Major, "Altruistic Healing"),
    MonksFocus(586, Valor, 3, 1, Major, "Monk's Focus"),
    GlacialHeart(587, Virtues, 2, 2, Major, "Glacial Heart"),
    StrengthOfTheFallen(588, Valor, 1, 0, Major, "Strength of the Fallen"),
    TenaciousDefense(589, Valor, 3, 2, Major, "Tenacious Defense"),
    CourageousReturn(594, Valor, 2, 0, Minor, "Courageous Return"),
    VirtuousSolace(603, Virtues, 2, 0, Major, "Virtuous Solace"),
    VirtueOfRetribution(604, Virtues, 2, 0, Minor, "Virtue of Retribution"),
    AbsoluteResolution(610, Virtues, 2, 1, Major, "Absolute Resolution"),
    IndomitableCourage(612, Virtues, 3, 2, Major, "Indomitable Courage"),
    MasterOfConsecrations(617, Virtues, 1, 2, Major, "Master of Consecrations"),
    PowerOfTheVirtuous(620, Virtues, 3, 0, Minor, "Power of the Virtuous"),
    InspiredVirtue(621, Virtues, 1, 0, Minor, "Inspired Virtue"),
    PermeatingWrath(622, Virtues, 3, 0, Major, "Permeating Wrath"),
    UnscathedContender(624, Virtues, 1, 0, Major, "Unscathed Contender"),
    RetaliatorySubconscious(625, Virtues, 1, 1, Major, "Retaliatory Subconscious"),
    FocusMastery(633, Valor, 1, 2, Major, "Focus Mastery"),
    ProtectorsImpact(654, Honor, 1, 2, Major, "Protector's Impact"),
    MetaphysicalRejuvenation(666, Chaos, 1, 0, Minor, "Metaphysical Rejuvenation"),
    IllusionaryMembrane(667, Chaos, 2, 0, Minor, "Illusionary Membrane"),
    ChaoticTransference(668, Chaos, 2, 1, Major, "Chaotic Transference"),
    ChaoticDampening(669, Chaos, 2, 2, Major, "Chaotic Dampening"),
    DescentIntoMadness(670, Chaos, 1, 0, Major, "Descent into Madness"),
    ChaoticInterruption(671, Chaos, 3, 0, Major, "Chaotic Interruption"),
    AuspiciousAnguish(673, Chaos, 2, 0, Major, "Auspicious Anguish"),
    PrismaticUnderstanding(674, Chaos, 3, 1, Major, "Prismatic Understanding"),
    IllusionaryDefense(675, Chaos, 1, 1, Major, "Illusionary Defense"),
    MasterOfManipulation(677, Chaos, 1, 2, Major, "Master of Manipulation"),
    MentalAnguish(680, Domination, 3, 1, Major, "Mental Anguish"),
    ImaginedBurden(681, Domination, 3, 0, Major, "Imagined Burden"),
    EmpoweredIllusions(682, Domination, 1, 1, Major, "Empowered Illusions"),
    IllusionOfVulnerability(685, Domination, 1, 0, Minor, "Illusion of Vulnerability"),
    ConfoundingSuggestions(686, Domination, 1, 0, Major, "Confounding Suggestions"),
    RendingShatter(687, Domination, 1, 2, Major, "Rending Shatter"),
    ThePledge(691, Illusions, 1, 2, Major, "The Pledge"),
    SuperiorityComplex(692, Dueling, 3, 0, Major, "Superiority Complex"),
    ShatteredConcentration(693, Domination, 2, 0, Major, "Shattered Concentration"),
    Dazzling(694, Domination, 2, 0, Minor, "Dazzling"),
    DuelistsDiscipline(700, Dueling, 1, 2, Major, "Duelist's Discipline"),
    PhantasmalFury(701, Dueling, 1, 0, Major, "Phantasmal Fury"),
    DeceptiveEvasion(704, Dueling, 3, 2, Major, "Deceptive Evasion"),
    DesperateDecoy(705, Dueling, 1, 1, Major, "Desperate Decoy"),
    CriticalInfusion(706, Dueling, 1, 0, Minor, "Critical Infusion"),
    MasterFencer(707, Dueling, 3, 0, Minor, "Master Fencer"),
    FencersFinesse(708, Dueling, 2, 2, Major, "Fencer's Finesse"),
    SharperImages(710, Dueling, 2, 0, Minor, "Sharper Images"),
    FuriousInterruption(712, Domination, 2, 2, Major, "Furious Interruption"),
    Egotism(713, Domination, 2, 1, Major, "Egotism"),
    ShatterStorm(721, Illusions, 1, 0, Major, "Shatter Storm"),
    EscapeArtist(722, Illusions, 2, 0, Major, "Escape Artist"),
    CompoundingPower(723, Illusions, 2, 0, Minor, "Compounding Power"),
    PhantasmalHaste(729, Illusions, 2, 1, Major, "Phantasmal Haste"),
    MasterOfMisdirection(731, Illusions, 3, 0, Minor, "Master of Misdirection"),
    PhantasmalForce(733, Illusions, 3, 0, Major, "Phantasmal Force"),
    CryOfPain(734, Illusions, 1, 0, Minor, "Cry of Pain"),
    RestorativeMantras(738, Inspiration, 1, 1, Major, "Restorative Mantras"),
    RestorativeIllusions(740, Inspiration, 2, 1, Major, "Restorative Illusions"),
    SympatheticVisage(744, Inspiration, 1, 2, Major, "Sympathetic Visage"),
    WardensFeedback(751, Inspiration, 2, 0, Major, "Warden's Feedback"),
    BlurredInscriptions(752, Inspiration, 3, 2, Major, "Blurred Inscriptions"),
    MaliciousSorcery(753, Illusions, 3, 2, Major, "Malicious Sorcery"),
    MedicsFeedback(756, Inspiration, 1, 0, Major, "Medic's Feedback"),
    MendersPurity(757, Inspiration, 1, 0, Minor, "Mender's Purity"),
    Transfusion(778, BloodMagic, 3, 2, Major, "Transfusion"),
    RitualOfLife(780, BloodMagic, 1, 0, Major, "Ritual of Life"),
    VampiricRituals(782, BloodMagic, 3, 0, Major, "Vampiric Rituals"),
    Vampiric(783, BloodMagic, 2, 0, Minor, "Vampiric"),
    QuickeningThirst(788, BloodMagic, 1, 1, Major, "Quickening Thirst"),
    LifeFromDeath(789, BloodMagic, 2, 0, Major, "Life from Death"),
    MarkOfEvasion(792, BloodMagic, 1, 0, Minor, "Mark of Evasion"),
    BansheesWail(799, BloodMagic, 2, 1, Major, "Banshee's Wail"),
    LingeringCurse(801, Curses, 3, 2, Major, "Lingering Curse"),
    BarbedPrecision(802, Curses, 1, 0, Minor, "Barbed Precision"),
    FuriousDemise(803, Curses, 2, 0, Minor, "Furious Demise"),
    TargetTheWeak(810, Curses, 3, 0, Minor, "Target the Weak"),
    Terror(812, Curses, 2, 2, Major, "Terror"),
    WeakeningShroud(813, Curses, 3, 0, Major, "Weakening Shroud"),
    ChillingDarkness(815, Curses, 1, 2, Major, "Chilling Darkness"),
    MasterOfCorruption(816, Curses, 2, 0, Major, "Master of Corruption"),
    FleshOfTheMaster(820, DeathMagic, 1, 0, Major, "Flesh of the Master"),
    AwakenThePain(829, Spite, 2, 1, Major, "Awaken the Pain"),
    SoulComprehension(839, DeathMagic, 2, 0, Minor, "Soul Comprehension"),
    DeathNova(842, DeathMagic, 3, 0, Major, "Death Nova"),
    CloseToDeath(853, Spite, 3, 1, Major, "Close to Death"),
    DeadlyStrength(855, DeathMagic, 2, 2, Major, "Deadly Strength"),
    ArmoredShroud(856, DeathMagic, 1, 0, Minor, "Armored Shroud"),
    PutridDefense(857, DeathMagic, 1, 1, Major, "Putrid Defense"),
    NecromanticCorruption(858, DeathMagic, 2, 0, Major, "Necromantic Corruption"),
    DarkDefiance(860, DeathMagic, 2, 1, Major, "Dark Defiance"),
    VitalPersistence(861, SoulReaping, 2, 1, Major, "Vital Persistence"),
    SoulBattery(874, SoulReaping, 3, 0, Minor, "Soul Battery"),
    UnyieldingBlast(875, SoulReaping, 1, 0, Major, "Unyielding Blast"),
    Gluttony(887, SoulReaping, 1, 0, Minor, "Gluttony"),
    SpeedOfShadows(888, SoulReaping, 1, 2, Major, "Speed of Shadows"),
    FootInTheGrave(889, SoulReaping, 3, 0, Major, "Foot in the Grave"),
    SinisterShroud(891, SoulReaping, 2, 0, Minor, "Sinister Shroud"),
    FearOfDeath(892, SoulReaping, 2, 2, Major, "Fear of Death"),
    DeathPerception(893, SoulReaping, 3, 1, Major, "Death Perception"),
    SoulBarbs(894, SoulReaping, 2, 0, Major, "Soul Barbs"),
    SoulMarks(898, SoulReaping, 1, 1, Major, "Soul Marks"),
    ChillOfDeath(899, Spite, 2, 0, Major, "Chill of Death"),
    SpitefulSpirit(903, Spite, 3, 2, Major, "Spiteful Spirit"),
    Dhuumfire(905, SoulReaping, 3, 2, Major, "Dhuumfire"),
    Dread(909, Spite, 2, 2, Major, "Dread"),
    ReapersMight(913, Spite, 1, 0, Minor, "Reaper's Might"),
    SpitefulTalisman(914, Spite, 1, 0, Major, "Spiteful Talisman"),
    DeathsEmbrace(915, Spite, 2, 0, Minor, "Death's Embrace"),
    SpitefulRenewal(916, Spite, 1, 1, Major, "Spiteful Renewal"),
    SiphonedPower(917, Spite, 3, 0, Minor, "Siphoned Power"),
    SignetsOfSuffering(919, Spite, 3, 0, Major, "Signets of Suffering"),
    WindborneNotes(964, NatureMagic, 2, 2, Major, "Windborne Notes"),
    SpiritedArrival(965, NatureMagic, 2, 1, Major, "Spirited Arrival"),
    ZephyrsSpeedBeastmastery(968, Beastmastery, 3, 1, Major, "Zephyr's Speed"),
    NaturalHealing(970, Beastmastery, 2, 2, Major, "Natural Healing"),
    LoudWhistle(974, Beastmastery, 2, 0, Minor, "Loud Whistle"),
    WiltingStrike(975, Beastmastery, 2, 0, Major, "Wilting Strike"),
    InstinctiveReaction(978, NatureMagic, 1, 1, Major, "Instinctive Reaction"),
    ClarionBond(986, Marksmanship, 1, 2, Major, "Clarion Bond"),
    PredatorsOnslaught(996, Marksmanship, 3, 0, Major, "Predator's Onslaught"),
    Farsighted(1000, Marksmanship, 2, 1, Major, "Farsighted"),
    BrutishSeals(1001, Marksmanship, 2, 0, Major, "Brutish Seals"),
    AlphaFocus(1009, Marksmanship, 2, 0, Minor, "Alpha Focus"),
    OpeningStrike(1010, Marksmanship, 1, 0, Minor, "Opening Strike"),
    PreciseStrike(1011, Marksmanship, 3, 0, Minor, "Precise Strike"),
    HuntersGaze(1014, Marksmanship, 1, 1, Major, "Hunter's Gaze"),
    Remorseless(1015, Marksmanship, 3, 1, Major, "Remorseless"),
    Spotter(1016, Skirmishing, 2, 0, Major, "Spotter"),
    Stoneform(1021, Marksmanship, 1, 0, Major, "Stoneform"),
    NaturesVengeance(1038, NatureMagic, 3, 0, Major, "Nature's Vengeance"),
    TwoHandedTraining(1047, Beastmastery, 2, 1, Major, "Two-Handed Training"),
    EvasivePurity(1054, NatureMagic, 2, 0, Major, "Evasive Purity"),
    Rejuvenation(1055, NatureMagic, 1, 0, Minor, "Rejuvenation"),
    FortifyingBond(1056, NatureMagic, 2, 0, Minor, "Fortifying Bond"),
    LingeringMagic(1059, NatureMagic, 3, 0, Minor, "Lingering Magic"),
    AlliesAid(1060, NatureMagic, 1, 2, Major, "Allies' Aid"),
    BountifulHunter(1062, NatureMagic, 1, 0, Major, "Bountiful Hunter"),
    QuickDraw(1064, Skirmishing, 3, 0, Major, "Quick Draw"),
    PetsProwess(1065, Beastmastery, 3, 0, Minor, "Pet's Prowess"),
    HonedAxes(1066, Beastmastery, 3, 2, Major, "Honed Axes"),
    PrimalReflexes(1067, Skirmishing, 1, 1, Major, "Primal Reflexes"),
    HuntersTactics(1068, Skirmishing, 3, 0, Minor, "Hunter's Tactics"),
    SharpenedEdges(1069, Skirmishing, 1, 0, Major, "Sharpened Edges"),
    MomentOfClarity(1070, Marksmanship, 2, 2, Major, "Moment of Clarity"),
    PotentAlly(1072, Beastmastery, 1, 1, Major, "Potent Ally"),
    TrappersExpertise(1075, Skirmishing, 1, 2, Major, "Trapper's Expertise"),
    TailWind(1080, Skirmishing, 1, 0, Minor, "Tail Wind"),
    FuriousGrip(1083, Skirmishing, 2, 0, Minor, "Furious Grip"),
    OakheartSalve(1086, WildernessSurvival, 1, 1, Major, "Oakheart Salve"),
    RuggedGrowth(1089, WildernessSurvival, 3, 0, Minor, "Rugged Growth"),
    CompanionsDefense(1090, WildernessSurvival, 2, 0, Minor, "Companion's Defense"),
    EmpathicBond(1094, WildernessSurvival, 3, 0, Major, "Empathic Bond"),
    NaturalVigor(1096, WildernessSurvival, 1, 0, Minor, "Natural Vigor"),
    SoftenTheFall(1098, WildernessSurvival, 1, 0, Major, "Soften the Fall"),
    TasteForDanger(1099, WildernessSurvival, 1, 2, Major, "Taste for Danger"),
    SharedAnguish(1100, WildernessSurvival, 2, 2, Major, "Shared Anguish"),
    Ambidexterity(1101, WildernessSurvival, 2, 0, Major, "Ambidexterity"),
    InstantReflexes(1112, Acrobatics, 1, 0, Major, "Instant Reflexes"),
    LeechingVenoms(1130, ShadowArts, 2, 1, Major, "Leeching Venoms"),
    CloakedInShadow(1134, ShadowArts, 3, 0, Major, "Cloaked in Shadow"),
    ShadowsRejuvenation(1135, ShadowArts, 3, 1, Major, "Shadow's Rejuvenation"),
    MeldWithShadows(1136, ShadowArts, 2, 0, Minor, "Meld with Shadows"),
    Kleptomaniac(1137, Trickery, 1, 0, Minor, "Kleptomaniac"),
    LeadAttacks(1157, Trickery, 3, 0, Minor, "Lead Attacks"),
    SleightOfHand(1158, Trickery, 3, 1, Major, "Sleight of Hand"),
    Uncatchable(1159, Trickery, 1, 0, Major, "Uncatchable"),
    MercifulAmbush(1160, ShadowArts, 1, 0, Major, "Merciful Ambush"),
    RendingShade(1162, ShadowArts, 3, 2, Major, "Rending Shade"),
    ThrillOfTheCrime(1163, Trickery, 1, 2, Major, "Thrill of the Crime"),
    DeadlyAmbition(1164, DeadlyArts, 1, 2, Major, "Deadly Ambition"),
    Improvisation(1167, DeadlyArts, 3, 1, Major, "Improvisation"),
    EvenTheOdds(1169, DeadlyArts, 2, 0, Major, "Even the Odds"),
    SunderingShade(1170, CriticalStrikes, 2, 0, Major, "Sundering Shade"),
    QuickPockets(1187, Trickery, 3, 0, Major, "Quick Pockets"),
    PressureStriking(1190, Trickery, 2, 2, Major, "Pressure Striking"),
    SwindlersEquilibrium(1192, Acrobatics, 2, 1, Major, "Swindler's Equilibrium"),
    AssassinsFury(1209, CriticalStrikes, 1, 0, Major, "Assassin's Fury"),
    UnrelentingStrikes(1210, CriticalStrikes, 2, 0, Minor, "Unrelenting Strikes"),
    HiddenKiller(1215, CriticalStrikes, 3, 1, Major, "Hidden Killer"),
    Preparedness(1232, Trickery, 2, 0, Minor, "Preparedness"),
    FelineGrace(1234, Acrobatics, 2, 0, Minor, "Feline Grace"),
    PainResponse(1237, Acrobatics, 1, 2, Major, "Pain Response"),
    AssassinsReward(1238, Acrobatics, 3, 0, Major, "Assassin's Reward"),
    ExpeditiousDodger(1240, Acrobatics, 1, 0, Minor, "Expeditious Dodger"),
    GuardedInitiation(1241, Acrobatics, 2, 0, Major, "Guarded Initiation"),
    EndlessStamina(1242, Acrobatics, 3, 0, Minor, "Endless Stamina"),
    DaggerTraining(1245, DeadlyArts, 1, 0, Major, "Dagger Training"),
    BurstOfAgility(1252, Trickery, 1, 1, Major, "Burst of Agility"),
    ExposedWeakness(1257, DeadlyArts, 3, 0, Minor, "Exposed Weakness"),
    SignetsOfPower(1267, CriticalStrikes, 1, 1, Major, "Signets of Power"),
    TwinFangs(1268, CriticalStrikes, 1, 2, Major, "Twin Fangs"),
    Executioner(1269, DeadlyArts, 3, 2, Major, "Executioner"),
    PracticedTolerance(1272, CriticalStrikes, 2, 1, Major, "Practiced Tolerance"),
    Mug(1276, DeadlyArts, 1, 1, Major, "Mug"),
    BountifulTheft(1277, Trickery, 2, 0, Major, "Bountiful Theft"),
    SerpentsTouch(1279, DeadlyArts, 1, 0, Minor, "Serpent's Touch"),
    LotusPoison(1280, DeadlyArts, 2, 0, Minor, "Lotus Poison"),
    KeenObserver(1281, CriticalStrikes, 1, 0, Minor, "Keen Observer"),
    FerociousStrikesCriticalStrikes(1282, CriticalStrikes, 3, 0, Minor, "Ferocious Strikes"),
    HiddenThief(1284, ShadowArts, 1, 2, Major, "Hidden Thief"),
    Trickster(1286, Trickery, 2, 1, Major, "Trickster"),
    VigorousRecovery(1289, Acrobatics, 1, 1, Major, "Vigorous Recovery"),
    HardToCatch(1290, Acrobatics, 2, 2, Major, "Hard to Catch"),
    PotentPoison(1291, DeadlyArts, 3, 0, Major, "Potent Poison"),
    PanicStrike(1292, DeadlyArts, 2, 1, Major, "Panic Strike"),
    ShadowsEmbrace(1293, ShadowArts, 1, 1, Major, "Shadow's Embrace"),
    ConcealingRestoration(1294, ShadowArts, 1, 0, Minor, "Concealing Restoration"),
    UpperHand(1295, Acrobatics, 3, 1, Major, "Upper Hand"),
    ShadowSavior(1297, ShadowArts, 2, 0, Major, "Shadow Savior"),
    AnkleShots(1299, CriticalStrikes, 2, 2, Major, "Ankle Shots"),
    FlickeringShadows(1300, ShadowArts, 2, 2, Major, "Flickering Shadows"),
    UnsuspectingFoe(1315, Arms, 2, 0, Major, "Unsuspecting Foe"),
    SunderingBurst(1316, Arms, 2, 1, Major, "Sundering Burst"),
    HeightenedFocus(1317, Discipline, 3, 1, Major, "Heightened Focus"),
    CrackShot(1329, Discipline, 1, 0, Major, "Crack Shot"),
    Blademaster(1333, Arms, 2, 2, Major, "Blademaster"),
    Opportunist(1334, Arms, 1, 2, Major, "Opportunist"),
    BurstPrecision(1336, Arms, 3, 0, Major, "Burst Precision"),
    Bloodlust(1337, Arms, 3, 0, Minor, "Bloodlust"),
    ForcefulGreatsword(1338, Strength, 2, 1, Major, "Forceful Greatsword"),
    FuriousBurst(1342, Arms, 1, 0, Minor, "Furious Burst"),
    DeepStrikes(1343, Arms, 2, 0, Minor, "Deep Strikes"),
    SignetMastery(1344, Arms, 1, 1, Major, "Signet Mastery"),
    Furious(1346, Arms, 3, 1, Major, "Furious"),
    AdrenalHealth(1348, Defense, 2, 0, Minor, "Adrenal Health"),
    ThickSkin(1350, Defense, 1, 0, Minor, "Thick Skin"),
    SunderingMace(1367, Defense, 2, 2, Major, "Sundering Mace"),
    DefyPain(1368, Defense, 2, 0, Major, "Defy Pain"),
    AxeMastery(1369, Discipline, 3, 0, Major, "Axe Mastery"),
    CullTheWeak(1372, Defense, 1, 2, Major, "Cull the Weak"),
    LastStand(1375, Defense, 3, 0, Major, "Last Stand"),
    ShieldMaster(1376, Defense, 1, 0, Major, "Shield Master"),
    ArmoredAttack(1379, Defense, 2, 1, Major, "Armored Attack"),
    SpikedArmor(1380, Defense, 3, 0, Minor, "Spiked Armor"),
    VengefulReturn(1381, Discipline, 1, 2, Major, "Vengeful Return"),
    WarriorsSprint(1413, Discipline, 1, 1, Major, "Warrior's Sprint"),
    VersatileRage(1415, Discipline, 1, 0, Minor, "Versatile Rage"),
    FastHands(1416, Discipline, 2, 0, Minor, "Fast Hands"),
    VersatilePower(1417, Discipline, 3, 0, Minor, "Versatile Power"),
    BerserkersPower(1437, Strength, 3, 0, Major, "Berserker's Power"),
    MercilessHammer(1440, Strength, 3, 2, Major, "Merciless Hammer"),
    PeakPerformance(1444, Strength, 1, 2, Major, "Peak Performance"),
    RecklessDodge(1446, Strength, 1, 0, Minor, "Reckless Dodge"),
    BraveStride(1447, Strength, 1, 0, Major, "Brave Stride"),
    BuildingMomentum(1448, Strength, 2, 0, Minor, "Building Momentum"),
    GreatFortitude(1449, Strength, 2, 2, Major, "Great Fortitude"),
    RestorativeStrength(1451, Strength, 1, 1, Major, "Restorative Strength"),
    PinnacleOfStrength(1453, Strength, 3, 0, Minor, "Pinnacle of Strength"),
    MightMakesRight(1454, Strength, 3, 1, Major, "Might Makes Right"),
    WoundingPrecision(1455, Arms, 1, 0, Major, "Wounding Precision"),
    LegSpecialist(1469, Tactics, 1, 0, Major, "Leg Specialist"),
    VigorousShouts(1470, Tactics, 3, 1, Major, "Vigorous Shouts"),
    RoaringReveille(1471, Tactics, 1, 2, Major, "Roaring Reveille"),
    SoldiersComfort(1474, Tactics, 1, 1, Major, "Soldier's Comfort"),
    ShrugItOff(1479, Tactics, 2, 1, Major, "Shrug It Off"),
    MarchingOrders(1480, Tactics, 1, 0, Minor, "Marching Orders"),
    MendingMight(1481, Tactics, 3, 0, Minor, "Mending Might"),
    EmpowerAllies(1482, Tactics, 2, 2, Major, "Empower Allies"),
    DoubledStandards(1484, Discipline, 2, 0, Major, "Doubled Standards"),
    Empowered(1485, Tactics, 2, 0, Minor, "Empowered"),
    WarriorsCunning(1486, Tactics, 2, 0, Major, "Warrior's Cunning"),
    ArcaneAbatement(1487, Arcane, 1, 2, Major, "Arcane Abatement"),
    DoggedMarch(1488, Defense, 1, 1, Major, "Dogged March"),
    DestructionOfTheEmpowered(1489, Discipline, 2, 1, Major, "Destruction of the Empowered"),
    Stormsoul(1502, Air, 2, 2, Major, "Stormsoul"),
    FreshAir(1503, Air, 3, 1, Major, "Fresh Air"),
    SerratedStones(1507, Earth, 1, 1, Major, "Serrated Stones"),
    DiamondSkin(1508, Earth, 3, 0, Major, "Diamond Skin"),
    PersistingFlames(1510, Fire, 3, 0, Major, "Persisting Flames"),
    BountifulPower(1511, Arcane, 3, 2, Major, "Bountiful Power"),
    OrbitalCommand(1541, Explosives, 3, 0, Major, "Orbital Command"),
    ResoundingTimbre(1606, Beastmastery, 1, 2, Major, "Resounding Timbre"),
    CleansingIre(1649, Defense, 3, 1, Major, "Cleansing Ire"),
    BurstMastery(1657, Discipline, 3, 2, Major, "Burst Mastery"),
    MartialCadence(1667, Tactics, 3, 0, Major, "Martial Cadence"),
    LightningRod(1672, Air, 3, 2, Major, "Lightning Rod"),
    ElementalContingency(1673, Arcane, 2, 1, Major, "Elemental Contingency"),
    StoneHeart(1674, Earth, 3, 2, Major, "Stone Heart"),
    BlindingAshes(1675, Fire, 3, 2, Major, "Blinding Ashes"),
    AquamancersTraining(1676, Water, 3, 0, Minor, "Aquamancer's Training"),
    ExperimentalTurrets(1678, Inventions, 2, 0, Major, "Experimental Turrets"),
    Gadgeteer(1679, Tools, 3, 2, Major, "Gadgeteer"),
    BunkerDown(1680, Inventions, 3, 1, Major, "Bunker Down"),
    ForceOfWill(1682, Honor, 3, 2, Major, "Force of Will"),
    CommunalDefenses(1684, Valor, 2, 2, Major, "Communal Defenses"),
    PurityOfBody(1685, Honor, 3, 0, Minor, "Purity of Body"),
    BountifulDisillusionment(1687, Chaos, 3, 2, Major, "Bountiful Disillusionment"),
    PowerBlock(1688, Domination, 3, 2, Major, "Power Block"),
    MaimTheDisillusioned(1690, Illusions, 2, 2, Major, "Maim the Disillusioned"),
    UnholyMartyr(1692, BloodMagic, 3, 1, Major, "Unholy Martyr"),
    PathOfCorruption(1693, Curses, 2, 1, Major, "Path of Corruption"),
    UnholySanctuary(1694, DeathMagic, 3, 2, Major, "Unholy Sanctuary"),
    ParasiticContagion(1696, Curses, 3, 1, Major, "Parasitic Contagion"),
    InvigoratingBond(1697, NatureMagic, 3, 2, Major, "Invigorating Bond"),
    LeadTheWind(1698, Marksmanship, 3, 2, Major, "Lead the Wind"),
    WildernessKnowledge(1699, WildernessSurvival, 3, 1, Major, "Wilderness Knowledge"),
    StridersDefense(1700, Skirmishing, 2, 1, Major, "Strider's Defense"),
    PoisonMaster(1701, WildernessSurvival, 3, 2, Major, "Poison Master"),
    InvigoratingPrecision(1702, CriticalStrikes, 3, 2, Major, "Invigorating Precision"),
    DontStop(1703, Acrobatics, 3, 2, Major, "Don't Stop"),
    RevealedTraining(1704, DeadlyArts, 2, 2, Major, "Revealed Training"),
    ShadowSiphoning(1705, ShadowArts, 3, 0, Minor, "Shadow Siphoning"),
    BewilderingAmbush(1706, Trickery, 3, 2, Major, "Bewildering Ambush"),
    DualWielding(1707, Arms, 3, 2, Major, "Dual Wielding"),
    RousingResilience(1708, Defense, 3, 2, Major, "Rousing Resilience"),
    BrawlersRecovery(1709, Discipline, 2, 2, Major, "Brawler's Recovery"),
    PhalanxStrength(1711, Tactics, 3, 2, Major, "Phalanx Strength"),
    DeterminedResolution(1713, Specialization.Retribution, 3, 0, Minor, "Determined Resolution"),
    SpontaneousDestruction(1714, Corruption, 2, 2, Major, "Spontaneous Destruction"),
    SwiftTermination(1715, Devastation, 3, 0, Major, "Swift Termination"),
    RisingMomentum(1716, Herald, 1, 2, Major, "Rising Momentum"),
    RoilingMists(1719, Invocation, 3, 2, Major, "Roiling Mists"),
    ManiacalPersistence(1720, Corruption, 3, 1, Major, "Maniacal Persistence"),
    PulsatingPestilence(1721, Corruption, 3, 2, Major, "Pulsating Pestilence"),
    TargetedDestruction(1724, Devastation, 2, 0, Minor, "Targeted Destruction"),
    AbyssalChill(1726, Corruption, 2, 1, Major, "Abyssal Chill"),
    DemonicResistance(1727, Corruption, 2, 0, Major, "Demonic Resistance"),
    CloseQuarters(1728, Specialization.Retribution, 1, 1, Major, "Close Quarters"),
    HardeningPersistence(1730, Herald, 2, 2, Major, "Hardening Persistence"),
    CleansingChannel(1732, Invocation, 1, 0, Major, "Cleansing Channel"),
    DraconicFortitude(1737, Herald, 2, 0, Minor, "Draconic Fortitude"),
    SharedEmpowerment(1738, Herald, 2, 0, Major, "Shared Empowerment"),
    DwarvenBattleTraining(1740, Specialization.Retribution, 2, 2, Major, "Dwarven Battle Training"),
    VenomEnhancement(1741, Corruption, 1, 2, Major, "Venom Enhancement"),
    ShiningAspects(1743, Herald, 2, 1, Major, "Shining Aspects"),
    YearningEmpowerment(1744, Corruption, 3, 0, Minor, "Yearning Empowerment"),
    ElevatedCompassion(1746, Herald, 3, 0, Major, "Elevated Compassion"),
    SongOfTheMists(1749, Invocation, 3, 0, Major, "Song of the Mists"),
    AssassinsAnnihilation(1754, Devastation, 3, 2, Major, "Assassin's Annihilation"),
    JadeEcho(1755, Devastation, 1, 2, Major, "Jade Echo"),
    UnwaveringAvoidance(1757, Specialization.Retribution, 2, 0, Minor, "Unwavering Avoidance"),
    FerociousAggression(1758, Invocation, 2, 0, Minor, "Ferocious Aggression"),
    RapidFlow(1760, Invocation, 2, 1, Major, "Rapid Flow"),
    RisingTide(1761, Invocation, 1, 1, Major, "Rising Tide"),
    Notoriety(1765, Devastation, 2, 1, Major, "Notoriety"),
    EyeForAnEye(1766, Specialization.Retribution, 2, 0, Major, "Eye for an Eye"),
    ViciousLacerations(1767, Devastation, 1, 1, Major, "Vicious Lacerations"),
    EmptyVessel(1769, Invocation, 3, 0, Minor, "Empty Vessel"),
    VersedInStone(1770, Specialization.Retribution, 3, 1, Major, "Versed in Stone"),
    DraconicEcho(1772, Herald, 3, 1, Major, "Draconic Echo"),
    SpiritBoon(1774, Invocation, 2, 0, Major, "Spirit Boon"),
    FerociousStrikesDevastation(1776, Devastation, 1, 0, Major, "Ferocious Strikes"),
    CrystalHarbinger(1777, Herald, 1, 0, Minor, "Crystal Harbinger"),
    InvokersRage(1778, Invocation, 1, 0, Minor, "Invoker's Rage"),
    ViciousReprisal(1779, Specialization.Retribution, 3, 0, Major, "Vicious Reprisal"),
    IncensedResponse(1781, Invocation, 2, 2, Major, "Incensed Response"),
    RetaliatoryEvasion(1782, Specialization.Retribution, 2, 1, Major, "Retaliatory Evasion"),
    EnduringRecovery(1783, Specialization.Retribution, 1, 0, Minor, "Enduring Recovery"),
    FierceInfusion(1784, Invocation, 1, 2, Major, "Fierce Infusion"),
    MaliciousReprisal(1786, Devastation, 2, 0, Major, "Malicious Reprisal"),
    ReinforcedPotency(1788, Herald, 3, 0, Minor, "Reinforced Potency"),
    DemonicDefiance(1789, Corruption, 1, 1, Major, "Demonic Defiance"),
    SteadfastRejuvenation(1790, Specialization.Retribution, 3, 2, Major, "Steadfast Rejuvenation"),
    ChargedMists(1791, Invocation, 3, 1, Major, "Charged Mists"),
    FocusedSiphoning(1792, Devastation, 3, 0, Minor, "Focused Siphoning"),
    ReplenishingDespair(1793, Corruption, 1, 0, Major, "Replenishing Despair"),
    DiabolicInferno(1795, Corruption, 3, 0, Major, "Diabolic Inferno"),
    RampantVex(1799, Corruption, 1, 0, Minor, "Rampant Vex"),
    Brutality(1800, Devastation, 3, 1, Major, "Brutality"),
    OpportuneExtraction(1801, Corruption, 2, 0, Minor, "Opportune Extraction"),
    AssassinsPresence(1802, Devastation, 2, 2, Major, "Assassin's Presence"),
    ForcefulPersistence(1803, Herald, 3, 2, Major, "Forceful Persistence"),
    CoreValue(1806, Herald, 1, 1, Major, "Core Value"),
    ExposeDefenses(1808, Devastation, 1, 0, Minor, "Expose Defenses"),
    SpiritualReckoning(1810, Specialization.Retribution, 1, 2, Major, "Spiritual Reckoning"),
    PlanarProtection(1811, Specialization.Retribution, 1, 0, Major, "Planar Protection"),
    EldersRespite(1813, Herald, 1, 0, Major, "Elder's Respite"),
    SereneRejuvenation(1814, Salvation, 3, 0, Minor, "Serene Rejuvenation"),
    GenerousAbundance(1815, Salvation, 3, 0, Major, "Generous Abundance"),
    HealersGift(1816, Salvation, 1, 0, Minor, "Healer's Gift"),
    ResilientSpirit(1817, Salvation, 2, 1, Major, "Resilient Spirit"),
    InvokingHarmony(1818, Salvation, 2, 2, Major, "Invoking Harmony"),
    WordsOfCensure(1819, Salvation, 2, 0, Major, "Words of Censure"),
    SelflessAmplification(1820, Salvation, 3, 2, Major, "Selfless Amplification"),
    LifeAttunement(1821, Salvation, 2, 0, Minor, "Life Attunement"),
    TranquilBalance(1822, Salvation, 1, 2, Major, "Tranquil Balance"),
    VitalBlessing(1823, Salvation, 1, 0, Major, "Vital Blessing"),
    BlindingTruths(1824, Salvation, 1, 1, Major, "Blinding Truths"),
    UnyieldingDevotion(1825, Salvation, 3, 1, Major, "Unyielding Devotion"),
    LongbowProficiency(1826, Dragonhunter, 0, 0, Minor, "Longbow Proficiency"),
    TorchProficiencyBerserker(1829, Berserker, 0, 0, Minor, "Torch Proficiency"),
    PrimalRage(1831, Berserker, 1, 0, Minor, "Primal Rage"),
    TakedownRound(1832, Tools, 2, 2, Major, "Takedown Round"),
    LotusTraining(1833, Daredevil, 3, 0, Major, "Lotus Training"),
    SoothingDetonation(1834, Inventions, 2, 1, Major, "Soothing Detonation"),
    ZealotsAggression(1835, Dragonhunter, 2, 1, Major, "Zealot's Aggression"),
    EnduranceThief(1837, Daredevil, 3, 0, Minor, "Endurance Thief"),
    DelayedReactions(1838, Chronomancer, 1, 0, Major, "Delayed Reactions"),
    TranscendentTempest(1839, Tempest, 3, 0, Major, "Transcendent Tempest"),
    VampiricPresence(1844, BloodMagic, 2, 2, Major, "Vampiric Presence"),
    HiddenBarbs(1846, Skirmishing, 2, 2, Major, "Hidden Barbs"),
    VirtuousAction(1848, Dragonhunter, 1, 0, Minor, "Virtuous Action"),
    AppliedForce(1849, Scrapper, 3, 2, Major, "Applied Force"),
    InspiringDistortion(1852, Inspiration, 2, 0, Minor, "Inspiring Distortion"),
    IronBlooded(1854, Alchemy, 3, 2, Major, "Iron Blooded"),
    KineticBattery(1856, Tools, 3, 0, Major, "Kinetic Battery"),
    TimeMarchesOn(1859, Chronomancer, 3, 0, Minor, "Time Marches On"),
    ObjectInMotion(1860, Scrapper, 2, 2, Major, "Object in Motion"),
    GoForTheEyes(1861, Beastmastery, 1, 0, Major, "Go for the Eyes"),
    LiveVicariously(1862, Druid, 2, 0, Minor, "Live Vicariously"),
    BitterChill(1863, Spite, 1, 2, Major, "Bitter Chill"),
    ChaoticPersistence(1865, Chaos, 3, 0, Minor, "Chaotic Persistence"),
    IllusionaryInspiration(1866, Inspiration, 3, 1, Major, "Illusionary Inspiration"),
    MassMomentum(1867, Scrapper, 1, 2, Major, "Mass Momentum"),
    DruidicClarity(1868, Druid, 1, 0, Major, "Druidic Clarity"),
    PersistenceOfMemory(1869, Illusions, 1, 1, Major, "Persistence of Memory"),
    PurityOfPurpose(1871, Alchemy, 3, 1, Major, "Purity of Purpose"),
    MechanizedDeployment(1872, Tools, 2, 0, Minor, "Mechanized Deployment"),
    CelestialBeing(1874, Druid, 1, 0, Minor, "Celestial Being"),
    BloodBond(1876, BloodMagic, 1, 2, Major, "Blood Bond"),
    ImpactSavant(1877, Scrapper, 3, 0, Minor, "Impact Savant"),
    ChemicalRounds(1878, Firearms, 1, 0, Major, "Chemical Rounds"),
    ShiversOfDread(1879, Reaper, 2, 0, Minor, "Shivers of Dread"),
    GlassCannon(1882, Explosives, 1, 2, Major, "Glass Cannon"),
    TerrifyingDescent(1883, Curses, 1, 0, Major, "Terrifying Descent"),
    StaffMaster(1884, Daredevil, 2, 0, Major, "Staff Master"),
    UnstableConduit(1886, Tempest, 1, 2, Major, "Unstable Conduit"),
    WeakeningStrikes(1887, Daredevil, 2, 0, Minor, "Weakening Strikes"),
    ViciousQuarry(1888, Skirmishing, 3, 2, Major, "Vicious Quarry"),
    BlindingDissipation(1889, Dueling, 2, 0, Major, "Blinding Dissipation"),
    Chronophantasma(1890, Chronomancer, 3, 2, Major, "Chronophantasma"),
    TempestuousAria(1891, Tempest, 2, 0, Major, "Tempestuous Aria"),
    BigBoomer(1892, Explosives, 2, 1, Major, "Big Boomer"),
    HavocSpecialist(1893, Daredevil, 2, 1, Major, "Havoc Specialist"),
    DefendersDogma(1896, Dragonhunter, 2, 0, Minor, "Defender's Dogma"),
    PiercingLight(1898, Dragonhunter, 1, 0, Major, "Piercing Light"),
    InvigoratedBulwark(1899, Honor, 1, 0, Major, "Invigorated Bulwark"),
    PackAlpha(1900, Beastmastery, 1, 0, Minor, "Pack Alpha"),
    AutomatedMedicalResponse(1901, Inventions, 1, 1, Major, "Automated Medical Response"),
    HarmoniousConduit(1902, Tempest, 2, 1, Major, "Harmonious Conduit"),
    NoQuarter(1904, CriticalStrikes, 3, 0, Major, "No Quarter"),
    ShroudKnight(1905, Reaper, 1, 0, Minor, "Shroud Knight"),
    HuntersFortification(1908, Dragonhunter, 3, 0, Major, "Hunter's Fortification"),
    ShieldProficiencyChronomancer(1910, Chronomancer, 0, 0, Minor, "Shield Proficiency"),
    SoaringDevastation(1911, Dragonhunter, 1, 2, Major, "Soaring Devastation"),
    LightOnYourFeet(1912, Skirmishing, 3, 1, Major, "Light on your Feet"),
    IllusionaryReversion(1913, Chronomancer, 2, 1, Major, "Illusionary Reversion"),
    HighCaliber(1914, Firearms, 1, 2, Major, "High Caliber"),
    HealingPrism(1915, Inspiration, 3, 0, Minor, "Healing Prism"),
    MedicalDispersionField(1916, Inventions, 3, 2, Major, "Medical Dispersion Field"),
    GyroscopicAcceleration(1917, Scrapper, 1, 0, Major, "Gyroscopic Acceleration"),
    DeathlyChill(1919, Reaper, 3, 1, Major, "Deathly Chill"),
    ShroudedRemoval(1922, DeathMagic, 1, 2, Major, "Shrouded Removal"),
    NoScope(1923, Firearms, 2, 2, Major, "No Scope"),
    PureOfSight(1926, Dragonhunter, 3, 0, Minor, "Pure of Sight"),
    FlowOfTime(1927, Chronomancer, 2, 0, Minor, "Flow of Time"),
    BloodyRoar(1928, Berserker, 3, 0, Major, "Bloody Roar"),
    BeyondTheVeil(1929, DeathMagic, 3, 0, Minor, "Beyond the Veil"),
    SanguineArray(1930, Firearms, 1, 1, Major, "Sanguine Array"),
    LastRites(1931, BloodMagic, 3, 0, Minor, "Last Rites"),
    BlightersBoon(1932, Reaper, 3, 0, Major, "Blighter's Boon"),
    MaraudersResilience(1933, Daredevil, 1, 0, Major, "Marauder's Resilience"),
    PrimalEchoes(1935, Druid, 1, 2, Major, "Primal Echoes"),
    ExcessiveEnergy(1936, Tools, 3, 0, Minor, "Excessive Energy"),
    GatheredFocus(1938, Tempest, 2, 0, Minor, "Gathered Focus"),
    CorruptersFervor(1940, DeathMagic, 3, 1, Major, "Corrupter's Fervor"),
    Fragility(1941, Domination, 3, 0, Minor, "Fragility"),
    LostTime(1942, Chronomancer, 3, 0, Major, "Lost Time"),
    Bulwark(1943, Dragonhunter, 2, 2, Major, "Bulwark"),
    ShortFuse(1944, Explosives, 2, 2, Major, "Short Fuse"),
    BeastlyWarden(1945, Beastmastery, 3, 0, Major, "Beastly Warden"),
    LockOn(1946, Tools, 2, 1, Major, "Lock On"),
    Minesweeper(1947, Explosives, 3, 2, Major, "Minesweeper"),
    HardyConduit(1948, Tempest, 3, 0, Minor, "Hardy Conduit"),
    BrawlersTenacity(1949, Daredevil, 1, 2, Major, "Brawler's Tenacity"),
    Ineptitude(1950, Dueling, 3, 1, Major, "Ineptitude"),
    HammerProficiency(1951, Scrapper, 0, 0, Minor, "Hammer Proficiency"),
    GaleSong(1952, Tempest, 1, 0, Major, "Gale Song"),
    DamageDampener(1954, Scrapper, 2, 0, Major, "Damage Dampener"),
    BigGameHunter(1955, Dragonhunter, 3, 2, Major, "Big Game Hunter"),
    StaffProficiencyDaredevil(1957, Daredevil, 0, 0, Minor, "Staff Proficiency"),
    FunctionGyro(1959, Scrapper, 1, 0, Minor, "Function Gyro"),
    EvasiveMirror(1960, Dueling, 2, 1, Major, "Evasive Mirror"),
    LatentStamina(1962, Tempest, 1, 1, Major, "Latent Stamina"),
    HeavyLight(1963, Dragonhunter, 3, 1, Major, "Heavy Light"),
    UnhinderedCombatant(1964, Daredevil, 3, 1, Major, "Unhindered Combatant"),
    StaffProficiencyDruid(1965, Druid, 0, 0, Minor, "Staff Proficiency"),
    SoulEater(1969, Reaper, 2, 0, Major, "Soul Eater"),
    SystemShocker(1971, Scrapper, 1, 1, Major, "System Shocker"),
    AuguryOfDeath(1974, Reaper, 1, 0, Major, "Augury of Death"),
    ImpactingDisruption(1975, Daredevil, 2, 2, Major, "Impacting Disruption"),
    SavageInstinct(1977, Berserker, 1, 2, Major, "Savage Instinct"),
    ImprovedAlacrity(1978, Chronomancer, 2, 2, Major, "Improved Alacrity"),
    OptimizedActivation(1979, Tools, 1, 0, Minor, "Optimized Activation"),
    ProtectedPhantasms(1980, Inspiration, 2, 2, Major, "Protected Phantasms"),
    AdaptiveArmor(1981, Scrapper, 3, 0, Major, "Adaptive Armor"),
    DulledSenses(1983, Dragonhunter, 1, 1, Major, "Dulled Senses"),
    PinpointDistribution(1984, Firearms, 2, 0, Major, "Pinpoint Distribution"),
    GreatswordProficiency(1985, Reaper, 0, 0, Minor, "Greatsword Proficiency"),
    ElementalBastion(1986, Tempest, 3, 2, Major, "Elemental Bastion"),
    AllsWellThatEndsWell(1987, Chronomancer, 1, 2, Major, "All's Well That Ends Well"),
    ProtectiveWard(1988, NatureMagic, 3, 1, Major, "Protective Ward"),
    NaturalMender(1992, Druid, 3, 0, Minor, "Natural Mender"),
    BurstOfAggression(1993, Berserker, 2, 0, Minor, "Burst of Aggression"),
    PhysicalSupremacy(1994, Daredevil, 1, 0, Minor, "Physical Supremacy"),
    TimeCatchesUp(1995, Chronomancer, 1, 1, Major, "Time Catches Up"),
    ReactiveLenses(1997, Tools, 1, 1, Major, "Reactive Lenses"),
    ExpertExamination(1999, Scrapper, 2, 1, Major, "Expert Examination"),
    BodyBlow(2000, Strength, 2, 0, Major, "Body Blow"),
    VerdantEtching(2001, Druid, 2, 1, Major, "Verdant Etching"),
    DeadOrAlive(2002, Berserker, 2, 2, Major, "Dead or Alive"),
    ElementalEnchantment(2004, Arcane, 3, 0, Minor, "Elemental Enchantment"),
    MentalDefense(2005, Inspiration, 3, 0, Major, "Mental Defense"),
    ThermalVision(2006, Firearms, 2, 1, Major, "Thermal Vision"),
    ChillingVictory(2008, Reaper, 2, 1, Major, "Chilling Victory"),
    DangerTime(2009, Chronomancer, 2, 0, Major, "Danger Time"),
    BloodReaction(2011, Berserker, 2, 0, Major, "Blood Reaction"),
    PlagueSending(2013, Curses, 1, 1, Major, "Plague Sending"),
    SpeedOfSynergy(2014, Scrapper, 2, 0, Minor, "Speed of Synergy"),
    InvigoratingTorrents(2015, Tempest, 2, 2, Major, "Invigorating Torrents"),
    CultivatedSynergy(2016, Druid, 1, 1, Major, "Cultivated Synergy"),
    ColdShoulder(2018, Reaper, 3, 0, Minor, "Cold Shoulder"),
    ChillingNova(2020, Reaper, 1, 1, Major, "Chilling Nova"),
    ReapersOnslaught(2021, Reaper, 3, 2, Major, "Reaper's Onslaught"),
    SeizeTheMoment(2022, Chronomancer, 3, 1, Major, "Seize the Moment"),
    EscapistsFortitude(2023, Daredevil, 1, 1, Major, "Escapist's Fortitude"),
    Singularity(2025, Tempest, 1, 0, Minor, "Singularity"),
    RelentlessPursuit(2026, Reaper, 1, 2, Major, "Relentless Pursuit"),
    SoothingPower(2028, Water, 3, 2, Major, "Soothing Power"),
    TimeSplitter(2030, Chronomancer, 1, 0, Minor, "Time Splitter"),
    DecimateDefenses(2031, Reaper, 2, 2, Major, "Decimate Defenses"),
    RefinedToxins(2032, WildernessSurvival, 2, 1, Major, "Refined Toxins"),
    LucidSingularity(2033, Tempest, 3, 1, Major, "Lucid Singularity"),
    MasterOfFragmentation(2035, Illusions, 3, 1, Major, "Master of Fragmentation"),
    WarhornProficiency(2036, Tempest, 0, 0, Minor, "Warhorn Proficiency"),
    HuntersDetermination(2037, Dragonhunter, 2, 0, Major, "Hunter's Determination"),
    KingOfFires(2038, Berserker, 3, 1, Major, "King of Fires"),
    LastBlaze(2039, Berserker, 1, 1, Major, "Last Blaze"),
    HeatTheSoul(2042, Berserker, 2, 1, Major, "Heat the Soul"),
    EternalChampion(2043, Berserker, 3, 2, Major, "Eternal Champion"),
    FatalFrenzy(2046, Berserker, 3, 0, Minor, "Fatal Frenzy"),
    BoundingDodger(2047, Daredevil, 3, 2, Major, "Bounding Dodger"),
    SmashBrawler(2049, Berserker, 1, 0, Major, "Smash Brawler"),
    ShieldProficiencyHerald(2050, Herald, 0, 0, Minor, "Shield Proficiency"),
    KineticStabilizers(2052, Scrapper, 3, 1, Major, "Kinetic Stabilizers"),
    CelestialShadow(2053, Druid, 2, 0, Major, "Celestial Shadow"),
    AncientSeeds(2055, Druid, 3, 2, Major, "Ancient Seeds"),
    NaturalStride(2056, Druid, 2, 2, Major, "Natural Stride"),
    GraceOfTheLand(2057, Druid, 3, 0, Major, "Grace of the Land"),
    LingeringLight(2058, Druid, 3, 1, Major, "Lingering Light"),
    DesertEmpowerment(2059, Scourge, 2, 0, Major, "Desert Empowerment"),
    MagebaneTether(2060, Spellbreaker, 3, 2, Major, "Magebane Tether"),
    SwiftRevenge(2061, Specialization.Weaver, 2, 1, Major, "Swift Revenge"),
    SwiftScholar(2062, Firebrand, 2, 0, Minor, "Swift Scholar"),
    WeightyTerms(2063, Firebrand, 2, 0, Major, "Weighty Terms"),
    PhotonicBlastingModule(2064, Holosmith, 3, 2, Major, "Photonic Blasting Module"),
    ThermalReleaseValve(2066, Holosmith, 3, 0, Major, "Thermal Release Valve"),
    SadisticSearing(2067, Scourge, 2, 1, Major, "Sadistic Searing"),
    NomadsEndurance(2069, Mirage, 2, 0, Minor, "Nomad's Endurance"),
    InfiniteHorizon(2070, Mirage, 3, 0, Major, "Infinite Horizon"),
    LiveFast(2071, Soulbeast, 1, 1, Major, "Live Fast"),
    UnstoppableUnion(2072, Soulbeast, 1, 2, Major, "Unstoppable Union"),
    AxeProficiencyFirebrand(2073, Firebrand, 0, 0, Minor, "Axe Proficiency"),
    FellBeacon(2074, Scourge, 1, 1, Major, "Fell Beacon"),
    UnrelentingCriticism(2075, Firebrand, 1, 0, Major, "Unrelenting Criticism"),
    StalwartSpeed(2076, Firebrand, 2, 1, Major, "Stalwart Speed"),
    ElementalRefreshment(2077, Specialization.Weaver, 2, 0, Minor, "Elemental Refreshment"),
    Payback(2078, Deadeye, 2, 1, Major, "Payback"),
    BloodFury(2079, Renegade, 1, 1, Major, "Blood Fury"),
    FeedFromCorruption(2080, Scourge, 3, 2, Major, "Feed from Corruption"),
    ElementalPolyphony(2081, Specialization.Weaver, 3, 0, Minor, "Elemental Polyphony"),
    RenewingOasis(2082, Mirage, 1, 1, Major, "Renewing Oasis"),
    IronSight(2084, Deadeye, 3, 0, Minor, "Iron Sight"),
    EssenceOfSpeed(2085, Soulbeast, 2, 1, Major, "Essence of Speed"),
    ArchivistOfWhispers(2086, Firebrand, 1, 2, Major, "Archivist of Whispers"),
    AxeProficiencyMirage(2087, Mirage, 0, 0, Minor, "Axe Proficiency"),
    DaggerProficiencySoulbeast(2088, Soulbeast, 0, 0, Minor, "Dagger Proficiency"),
    PurityOfWord(2089, Firebrand, 1, 0, Minor, "Purity of Word"),
    WovenStride(2090, Specialization.Weaver, 3, 1, Major, "Woven Stride"),
    CrystalConfigurationZephyr(2091, Holosmith, 2, 2, Major, "Crystal Configuration: Zephyr"),
    Heartpiercer(2092, Renegade, 2, 1, Major, "Heartpiercer"),
    BeQuickOrBeKilled(2093, Deadeye, 3, 1, Major, "Be Quick or Be Killed"),
    Vindication(2094, Renegade, 3, 0, Major, "Vindication"),
    SunAndMoonStyle(2095, Spellbreaker, 2, 2, Major, "Sun and Moon Style"),
    BloodAsSand(2096, Scourge, 3, 0, Minor, "Blood as Sand"),
    SlowCounter(2097, Spellbreaker, 2, 1, Major, "Slow Counter"),
    MirroredAxes(2098, Mirage, 2, 2, Major, "Mirrored Axes"),
    ShortBowProficiency(2099, Renegade, 0, 0, Minor, "Short Bow Proficiency"),
    LastingLegacy(2100, Renegade, 3, 1, Major, "Lasting Legacy"),
    LiberatorsVow(2101, Firebrand, 1, 1, Major, "Liberator's Vow"),
    NourishingAshes(2102, Scourge, 1, 2, Major, "Nourishing Ashes"),
    CrystalConfigurationStorm(2103, Holosmith, 2, 0, Major, "Crystal Configuration: Storm"),
    StoicDemeanor(2105, Firebrand, 3, 0, Major, "Stoic Demeanor"),
    SolarFocusingLens(2106, Holosmith, 1, 2, Major, "Solar Focusing Lens"),
    PureStrike(2107, Spellbreaker, 1, 0, Major, "Pure Strike"),
    AllForOne(2108, Renegade, 2, 2, Major, "All for One"),
    Weaver(2109, Specialization.Weaver, 1, 0, Minor, "Weaver"),
    RiddleOfSand(2110, Mirage, 1, 2, Major, "Riddle of Sand"),
    MaleficentSeven(2111, Deadeye, 3, 0, Major, "Maleficent Seven"),
    SandSavant(2112, Scourge, 3, 0, Major, "Sand Savant"),
    ElusiveMind(2113, Mirage, 3, 1, Major, "Elusive Mind"),
    LightDensityAmplifier(2114, Holosmith, 1, 0, Major, "Light Density Amplifier"),
    MastersFortitude(2115, Specialization.Weaver, 1, 2, Major, "Master's Fortitude"),
    LegendaryLore(2116, Firebrand, 2, 2, Major, "Legendary Lore"),
    SpeedOfSand(2117, Mirage, 3, 0, Minor, "Speed of Sand"),
    SilentScope(2118, Deadeye, 2, 0, Major, "Silent Scope"),
    SecondSkin(2119, Soulbeast, 2, 0, Major, "Second Skin"),
    WroughtIronWill(2120, Renegade, 1, 2, Major, "Wrought-Iron Will"),
    SandSage(2121, Scourge, 2, 0, Minor, "Sand Sage"),
    LasersEdge(2122, Holosmith, 3, 0, Minor, "Laser's Edge"),
    HeraldOfSorrow(2123, Scourge, 2, 2, Major, "Herald of Sorrow"),
    DaggerProficiencySpellbreaker(2124, Spellbreaker, 0, 0, Minor, "Dagger Proficiency"),
    SwordProficiencyHolosmith(2125, Holosmith, 0, 0, Minor, "Sword Proficiency"),
    LossAversion(2126, Spellbreaker, 2, 0, Major, "Loss Aversion"),
    TwiceAsVicious(2127, Soulbeast, 3, 0, Minor, "Twice as Vicious"),
    LeaderOfThePack(2128, Soulbeast, 3, 1, Major, "Leader of the Pack"),
    RifleProficiency(2129, Deadeye, 0, 0, Minor, "Rifle Proficiency"),
    AttackersInsight(2130, Spellbreaker, 3, 0, Minor, "Attacker's Insight"),
    ElementsOfRage(2131, Specialization.Weaver, 3, 0, Major, "Elements of Rage"),
    SuddenReversal(2133, Renegade, 2, 0, Major, "Sudden Reversal"),
    FreshReinforcement(2134, Soulbeast, 1, 0, Major, "Fresh Reinforcement"),
    HeatTherapy(2135, Holosmith, 2, 0, Minor, "Heat Therapy"),
    OneInTheChamber(2136, Deadeye, 1, 2, Major, "One in the Chamber"),
    EnhancedCapacityStorageUnit(2137, Holosmith, 3, 1, Major, "Enhanced Capacity Storage Unit"),
    InvigoratingStrikes(2138, Specialization.Weaver, 3, 2, Major, "Invigorating Strikes"),
    NoEscape(2140, Spellbreaker, 1, 2, Major, "No Escape"),
    SelfDeception(2141, Mirage, 1, 0, Major, "Self-Deception"),
    BrutalMomentum(2142, Renegade, 3, 0, Minor, "Brutal Momentum"),
    OppressiveSuperiority(2143, Soulbeast, 3, 2, Major, "Oppressive Superiority"),
    TorchProficiencyScourge(2144, Scourge, 0, 0, Minor, "Torch Proficiency"),
    MaliciousIntent(2145, Deadeye, 1, 0, Major, "Malicious Intent"),
    FireForEffect(2146, Deadeye, 3, 2, Major, "Fire for Effect"),
    MantleOfSand(2147, Scourge, 1, 0, Minor, "Mantle of Sand"),
    ImbuedHaste(2148, Firebrand, 3, 0, Minor, "Imbued Haste"),
    SwordProficiencyWeaver(2149, Specialization.Weaver, 0, 0, Minor, "Sword Proficiency"),
    MirageCloak(2150, Mirage, 1, 0, Minor, "Mirage Cloak"),
    ElevatedBond(2151, Soulbeast, 1, 0, Minor, "Elevated Bond"),
    CrystalConfigurationEclipse(2152, Holosmith, 2, 1, Major, "Crystal Configuration: Eclipse"),
    GuardCounter(2153, Spellbreaker, 1, 1, Major, "Guard Counter"),
    EndlessEnmity(2154, Renegade, 2, 0, Minor, "Endless Enmity"),
    EternalBond(2155, Soulbeast, 3, 0, Major, "Eternal Bond"),
    FuriousStrength(2156, Soulbeast, 2, 0, Minor, "Furious Strength"),
    PrismaticConverter(2157, Holosmith, 1, 1, Major, "Prismatic Converter"),
    PhotonProjector(2158, Holosmith, 1, 0, Minor, "Photon Projector"),
    Loremaster(2159, Firebrand, 3, 2, Major, "Loremaster"),
    Premeditation(2160, Deadeye, 2, 2, Major, "Premeditation"),
    PredatorsCunning(2161, Soulbeast, 2, 2, Major, "Predator's Cunning"),
    DispellingForce(2162, Spellbreaker, 2, 0, Minor, "Dispelling Force"),
    EnchantmentCollapse(2163, Spellbreaker, 3, 0, Major, "Enchantment Collapse"),
    DemonicLore(2164, Scourge, 3, 1, Major, "Demonic Lore"),
    ElementalPursuit(2165, Specialization.Weaver, 1, 1, Major, "Elemental Pursuit"),
    AshenDemeanor(2166, Renegade, 1, 0, Major, "Ashen Demeanor"),
    AbrasiveGrit(2167, Scourge, 1, 0, Major, "Abrasive Grit"),
    RevengeCounter(2168, Spellbreaker, 3, 1, Major, "Revenge Counter"),
    DuneCloak(2169, Mirage, 3, 2, Major, "Dune Cloak"),
    BolsteredElements(2170, Specialization.Weaver, 2, 2, Major, "Bolstered Elements"),
    DeadeyesGaze(2171, Deadeye, 1, 0, Minor, "Deadeye's Gaze"),
    RenewingGaze(2172, Deadeye, 2, 0, Minor, "Renewing Gaze"),
    CollateralDamage(2173, Deadeye, 1, 1, Major, "Collateral Damage"),
    MirageMantle(2174, Mirage, 2, 1, Major, "Mirage Mantle"),
    SpellbreakersConviction(2175, Spellbreaker, 1, 0, Minor, "Spellbreaker's Conviction"),
    SuperiorElements(2177, Specialization.Weaver, 1, 0, Major, "Superior Elements"),
    DesertDistortion(2178, Mirage, 2, 0, Major, "Desert Distortion"),
    Quickfire(2179, Firebrand, 3, 1, Major, "Quickfire"),
    WeaversProwess(2180, Specialization.Weaver, 2, 0, Major, "Weaver's Prowess"),
    AmbushCommander(2181, Renegade, 1, 0, Minor, "Ambush Commander"),
    RighteousRebel(2182, Renegade, 3, 2, Major, "Righteous Rebel");

    private static final Map<Integer,Trait> ID_LOOKUP_MAP = new HashMap<>();

    static {
        Stream.of(values()).forEach(trait -> ID_LOOKUP_MAP.put(trait.id, trait));
    }

    private final int id;
    private final Specialization specialization;
    private final int tier;
    private final int order;
    private final TraitSlot slot;
    private final String name;

    Trait(int id, Specialization specialization, int tier, int order, TraitSlot slot, String name) {
        this.id = id;
        this.specialization = specialization;
        this.tier = tier;
        this.order = order;
        this.slot = slot;
        this.name = name;
    }

    public int getId() {
        return id;
    }

    public Specialization getSpecialization() {
        return specialization;
    }

    public int getTier() {
        return tier;
    }

    public int getOrder() {
        return order;
    }

    public TraitSlot getSlot() {
        return slot;
    }

    public String getName() {
        return name;
    }

    public static Trait getById(int id) {
        return ID_LOOKUP_MAP.get(id);
    }
}
